### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by sscarduzio** [cloudfoundry/bosh-s3cli#29]
Hi, how can I download an arm64 compatible version of this tool (for Linux)?

**Comment by rkoster** [comment]
As mention [here](https://github.com/cloudfoundry/bosh-s3cli/issues/28#issuecomment-873188886) we are not looking to add any features to this cli, which do not align with the requirements put forward by the bosh stemcell. Since BOSH does not support arm64 stemcells there are no plans to publish those binaries.

**Comment by sscarduzio** [comment]
OK I understand, @rkoster. I ended up spinning a graviton EC2 machine and typed the "go get" command. 
I actually like this tiny program because I use it is simple, small and its API does not change in time. It's ideal for my CI pipeline ;)
